/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stringObject */

#ifndef _Included_stringObject
#define _Included_stringObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     stringObject
 * Method:    sayHello
 * Signature: (LstringObject;)V
 */
JNIEXPORT void JNICALL Java_stringObject_sayHello
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
